### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by yaa110** [AntonioRedondo/AnotherMonitor#1]
Unfortunately, it crashes on start. Tested device was an ASUS MemoPad HD7 (ME173X) running Android 4.2.2.

**Comment by AntonioRedondo** [comment]
Thank you for opening the issue @yaa110.

It's still a bit hard to know what could be the cause of the crash with this little information. If you have some chance perhaps you may be interested on connecting the tablet to your computer and see the ADB log from IntelliJ or Eclipse when you open AnotherMonitor. Then you could copy and paste the exception thrown here.

**Comment by yaa110** [comment]
```
04-02 20:49:29.167  26847-26904/? E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-2889
    java.lang.IllegalArgumentException: Underflow in restoreToCount
            at android.graphics.Canvas.restoreToCount(Native Method)
            at android.view.TextureView.unlockCanvasAndPost(TextureView.java:687)
            at org.anothermonitor.ActivityMain$2$1.run(ActivityMain.java:140)
04-02 20:49:29.181     442-1693/? W/ActivityManager﹕ Force finishing activity org.anothermonitor/.ActivityMain
```

**Comment by AntonioRedondo** [comment]
On commit https://github.com/AntonioRedondo/AnotherMonitor/commit/5023b3d187c8ce0ac239de686a38e217910e7def I've made some changes which should fix the issue (not published yet on Google Play). However I'm unable to reproduce the behaviour. So not sure whether the bug's actually fixed or not.

You might be interested on collaborating: https://github.com/AntonioRedondo/AnotherMonitor#contribute. But for this issue, just by compiling from the last source code, running the APK on your tablet and seeing whether it runs or not would be really helpful.

**Comment by yaa110** [comment]
Thank you for considering this issue. As you catched the IllegalArgumentException,  the application starts without force closing, but the plots would not be drawn if the exception occurred.

**Comment by AntonioRedondo** [comment]
Ouch! No idea why the bug is happening on this Asus device. I've added a 'Known issues' section on the project's README.md file. I hope it's not a common issue among Android devices.
