### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [AntonioRedondo/AnotherMonitor#6]
Hi @AntonioRedondo 

I found [this app](https://play.google.com/store/apps/details?id=com.ingic.deviceanalyzer) on the Google Play Store. This guy just took your source code and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app.

Maybe add a screenshot, a link to this repo...

**Comment by AntonioRedondo** [comment]
Hey @Poussinou,

Thank you for bringing this to my attention. I cannot believe that a big company like Ingic is blatantly ripping my app in such a way.

I've reported this to Google.

**Comment by Poussinou** [comment]
At least 4 open-source apps are currently uploaded on their Google developer account... Yours is just one of them...

If you have some time, you can spend one hour or so to review other apps about android monitoring on the Store. Some of them might be "Another monitor" but with ads in it and without gnu gpl license... Then report them to Google. (It's a little bit boring, but useful...) If you do so, please copy past the links of the apps you reported here, so that I can track the fake developers ;) thanks

**Comment by Poussinou** [comment]
PS : btw, thanks for this app ;)

**Comment by AntonioRedondo** [comment]
Yeah, I see [this other app of them](https://play.google.com/store/apps/details?id=com.ingic.pacer) is stolen from [here](https://play.google.com/store/apps/details?id=de.j4velin.pedometer).

Which are the other apps?

**Comment by Poussinou** [comment]
* [this one](https://play.google.com/store/apps/details?id=com.ingic.forecastnow) from [here](https://github.com/martykan/forecastie)
* [this one](https://play.google.com/store/apps/details?id=com.ingic.allconvertor) from [here](https://github.com/physphil/UnitConverterUltimate)
* [this one](https://play.google.com/store/apps/details?id=com.ingic.smartstock) from [here](https://github.com/premnirmal/StockTicker)
* [this one](https://play.google.com/store/apps/details?id=com.ingic.colorflood) from [here](https://github.com/GunshipPenguin/open_flood)
* [this one](https://play.google.com/store/apps/details?id=com.ingic.minitask) from [here](https://github.com/avjinder/Minimal-Todo)
* [this one](https://play.google.com/store/apps/details?id=com.ingic.easysoundrecorder) from [here](https://github.com/dkim0419/SoundRecorder)

More than four in fact, sorry for this mistake^^

**Comment by AntonioRedondo** [comment]
The copy app is gone: https://play.google.com/store/apps/details?id=com.ingic.deviceanalyzer    🎉 🎆 🍾

**Comment by Poussinou** [comment]
Great !
Do not forget, if one day you find other violations like this, ping me ! :smiley: 
I'll close now, but do not hesitate to reopen if needed
